title: Project

columns:
  main:
    width: 1/2
    sections:
      info:
        type: fields
        fields:
          Title:
            type: text
          Cameraused:
            type: text
          FieldTitle1:
            type: text
          FieldDescription1:
            type: text
          FieldTitle2:
            type: text
          FieldDescription2:
            type: text
          FieldTitle3:
            type: text
          FieldDescription3:
            type: text
          Videolength:
            type: text
          Videoembedurl:
            type: text
            icon: video
