title: project

sections:
  info:
    type: fields
    fields:
      title:
        type: text
      camera used:
        type: text
      director:
        type: text
      assistant:
        type: text
      lighting:
        type: text
      videolength:
        type: text
      videoembedurl:
        type: text
